name: Remote SSH Command

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-cinemaempoa:
    if: ${{ github.repository == 'cumbucadev/cinemaempoa' }}
    name: Deploy Cinema Em POA
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd cinemaempoa
            git pull
            
            echo "ğŸ”„ Building Docker image..."
            docker compose -f docker-compose.production.yml build flask
            
            echo "ğŸ”„ Running database migrations..."
            docker compose -f docker-compose.production.yml run --rm flask flask --app flask_backend db-upgrade
            echo "âœ… Migrations completed."
            
            echo "ğŸš€ Starting application..."
            docker compose -f docker-compose.production.yml up -d flask

            echo "ğŸ” Truncating Docker container logs..."
            truncate -s 0 /var/lib/docker/containers/*/*-json.log
            echo "âœ… Logs cleared."
            
            echo "ğŸ—‘ï¸  Removing all stopped containers..."
            docker container prune -f
            echo "âœ… Stopped containers removed."
            
            echo "ğŸ§¹ Cleaning up old Docker images (older than 12h)..."
            docker image prune -a -f --filter "until=12h"
            echo "âœ… Old unused images cleaned up."
            
            echo "ğŸ‰ Docker cleanup complete!"
