name: Fetch Posters

on:
  schedule:
    - cron: "5 12 * * *" # Everyday at 12:05
  workflow_dispatch:

jobs:
  update-sitemaps:
    if: ${{ github.repository == 'cumbucadev/cinemaempoa' }}
    name: Fetch Posters
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker exec cinemaempoa_flask bash -c "flask --app flask_backend fetch-posters"
